FROM registry.access.redhat.com/ubi9/ubi:9.0.0-1468

RUN adduser \
  --no-create-home \
  --system \
  --shell /usr/sbin/nologin \
  python-server && \
  mkdir /server && \
  chown -R 'python-server:python-server' /server

WORKDIR /server

USER python-server

CMD ["python3", "-m", "http.server"]
